[package]
name = "joystick"
version = "0.1.0"
edition = "2021"
authors = ["YdrMaster <ydrml@hotmail.com>"]
readme = "README.md"

[dependencies]
pm1-sdk = { path = "../../" }
joystick-win = { path = "../../../joystick-win" }
